import { Feature } from "./feature";

export class Specialization extends Feature {
}

export enum TypeSpecialization {
    ACROBATIC = "ACROBATIC",
    ATHLETIC = "ATHLETIC",
    COMBAT_MELEE = "COMBAT_MELEE",
    COMBAT_RANGER = "COMBAT_RANGER",
    COMBAT_DISARMED = "COMBAT_DISARMED",
    CHEAT = "CHEAT",
    TACTICAL = "TACTICAL",
    STEALTH = "STEALTH",
    INTIMIDATION = "INTIMIDATION",
    INTUITION = "INTUITION",
    INVESTIGATION = "INVESTIGATION",
    PERCEPTION = "PERCEPTION",
    PERSUASION = "PERSUASION",
    COMBAT_WEAPONS = "COMBAT_WEAPONS",
    CRITICAL_DAMAGE = 'CRITICAL',
    CRITICAL_RATE = 'CRITICAL_RATE',
    MEDICINE = 'MEDICINE'
}